### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by EyalFaygen**

### CODE REVIEW

**Comment by EyalFaygen** [comment]
first commit includes all the angular packages, no need to review it.
everything alse needs review.

**Comment by HadadIdan** [comment]
I briefly looked at all of  the commits (except the first one, as you mentioned), however I don't understand the language enough to help you. As it is the front-end, how about I check it by actually seeing the result, instead of "reading" it? This way I will be able to construct actual criticism.

**Comment by EyalFaygen** [comment]
end result:
image

also, all the tabs in the navbar are clickable

**Comment by HadadIdan** [comment]
Great job, as it is front end and mostly design, I reviewed it by looking at the end result, and it seems great!

**Pull request merged**
