### PR TITLE
Change to spartanizer rule, OurServer, added docs

### PR DESCRIPTION
**Pull request by HadadIdan**
Changed a line in OurServer for it to work as expected.
Removed a spartanizer rule (since you can't surpress tips) "ClassIntanceCreationBoxedValueTypes" as
in some cases (like the one explained in #187) it changes the functionality
of line.
Added many more Docs, but not every Doc, since the old classes of
Spartanizer didn't follow Java Doc rules perfectly...

### CODE REVIEW

**Comment by HadadIdan** [comment]
This pull request **fixes 1 alert** when merging 60925f8fb7eff05f46cea4065547447623bab825 into a3a188f428a603757befb272476799306e427ad2 - [view on LGTM.com](https://lgtm.com/projects/g/TechnionYP5779/team6/rev/pr-9ea9b0fe9a34fe2ca9bb8e842e3e9c1dbaf428ce)

**fixed alerts:**

* 1 for Implicit conversion from array to string

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by EyalFaygen** [comment]
why do we need all the javadoc output if we can generate it whenever we need?

**Comment by HadadIdan** [comment]
@EyalFaygen 
A) To prevent the need to generate them
B) Current settings i used to generate enable the generation of some docs that can't be generated
without those exact settings.
@EyalFaygen

**Comment by EyalFaygen** [comment]
ok.
reviewed everything that is not a javadoc auto-generated and it looks good

**Comment by HadadIdan** [comment]
This pull request **fixes 1 alert** when merging ad394ee60056b64e07203b0ace71b3791cd2580c into 6a5f8a33707e0957bbb3089571f1b156e9be983c - [view on LGTM.com](https://lgtm.com/projects/g/TechnionYP5779/team6/rev/pr-91121e057331167562a683ec1f13422abd3e0885)

**fixed alerts:**

* 1 for Implicit conversion from array to string

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
